# Generated by Django 4.0.2 on 2022-02-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=30)),
                ('availability', models.BooleanField(default=True)),
                ('needing_repair', models.BooleanField(default=True)),
                ('durability', models.IntegerField()),
                ('max_durability', models.IntegerField()),
                ('mileage', models.IntegerField(null=True)),
                ('price', models.IntegerField()),
                ('minimum_rent_period', models.IntegerField()),
            ],
        ),
    ]
